# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c028b5547d8c2253df47af8b54e1472fe1ac372090b065931dac66b8eab50077815f1e3fe62c19d450964aa2b6cca349fd8dfb35c866af1b6bd120eebc22d1c5

test:
  secret_key_base: 145b2523f246a22ff6747de5dbd759a8b480f31bdb21fed8eceacd46e746036cd3a3be25575c2fdee70027420e64376e52538a2bb36c0891bd2b72eb112f694b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
